print("abreviaturas en python")
print("\n\tx+=1 equivalente a x=x+1")
print("\n\ty+=2 equivalente a y=y+2")
print("\n\tsi un numero lleva guiones bajos python lo entiende como cifra contínua")
print("\tPor ejemplo 14_000_000_000 equivale a 14000000000")
print("\n\t x, y, z =0,0,0 equivale a la asignación de variables:")
print("\t\t\t\t\t\t\t\tx=0")
print("\t\t\t\t\t\t\t\ty=0")
print("\t\t\t\t\t\t\t\tz=0")
print("\n")